### ISSUE TITLE
[Crash] RemoteSourceImpl.java line 29

### ISSUE THREAD

**Issue by yoonhok524** [alan-project/RickAndMorty#72]
https://console.firebase.google.com/u/0/project/rick-morty-guidance/crashlytics/app/android:net.alanproject.rickandmorty/issues/09fd4e0544e495fe2ce5d32f2f1ab7eb?time=last-thirty-days&sessionEventKey=61EDF67402280001314AD1067C541A48_1635012780270934090

```
Caused by java.lang.NullPointerException
domainVersionConfigModel must not be null
  net.alanproject.data.source.remote.RemoteSourceImpl.getVersionConfig (RemoteSourceImpl.java:29)
  net.alanproject.data.repository.CartoonRepositoryImpl.getVersionConfig (CartoonRepositoryImpl.java:29)
  net.alanproject.domain.usecases.impl.GetVersionConfigUsecase.getNewVersionConfig (GetVersionConfigUsecase.java:29)
  net.alanproject.rickandmorty.ui.main.MainViewModel.checkNewVersion (MainViewModel.java:29)
  net.alanproject.rickandmorty.ui.main.MainActivity.onCreate (MainActivity.java:29)
  android.app.Activity.performCreate (Activity.java:8207)
```

**Comment by alan-project** [comment]
윤호님 안녕하세요

위 문제는 firebase에서 config를 제대로 못가져올때 발생하는것 같습니다.
데이터를 못가져오면 하드코딩한 값을 리턴하게 했습니다. 
좀 지저분해 보이긴하는데..이렇게 해도 괜찮을까요..?
ScopeFunction으로 뭔가 멋지게 쓰고 싶은데 잘 안되네요 크윽.

```kotlin
     override fun getVersionConfig(): DomainVersionConfigModel {

        Timber.d("getVersionConfig IN")
        var jsonString: String = remoteConfig.getString("version_update2")
        
        //추가된 코드
        if (jsonString.isNullOrEmpty()) jsonString =
            "{latest_version:4, force_update:false,force_update_target:[0,0]}"

        Timber.d("jsonString: $jsonString")

        val domainVersionConfigModel = Gson().fromJson(
            jsonString,
            DomainVersionConfigModel::class.java
        )

        Timber.d("domainVersionConfigModel: $domainVersionConfigModel")
        return domainVersionConfigModel
    }
```

**Comment by yoonhok524** [comment]
@alan-project 

음... 다른 것부터 이야기를 먼저 하면 `master` 브랜치로 commit 하는 것은 되도록 피하셨으면 해요.
혼자 하는 프로젝트라 그게 편하고 문제도 없긴 합니다만,
상우님께서 팀원들과 git으로 협업을 충분히 경험하신 것이 아니기에 (PR, 코드 리뷰 등)
되도록 혼자할 때에도 PR을 올려 이력 관리를 하는 것을 습관화하는 것이 좋을 것 같습니다.
(아마 실무에서는 `master` 브랜치에 commit 권한 자체가 막혀있을 거에요.)

1. 보통 Jira에 문제가 등록되면 (github issue에 문제가 꽂히면)
2. 관련된 브랜치를 따고,
3. 문제를 수정 후
4. PR을 올립니다.
5. 코드 리뷰를 거치고
6. merge를 합니다.

단순히 이것 외에도 해당 PR과 Jira 티켓 (github issue) 사이에 link가 생기기 때문에
어떤 이슈를 어떤 PR에서 수정했는지 트래킹이 더 수월해져요.
반면 지금 `master` 브랜치에 바로 커밋하신 내용은 제가 리뷰하기도 어렵고,
상우님께서 코드 조각을 댓글로 올려주셔야 인지 가능한 부분도 있고요.

**Comment by yoonhok524** [comment]
@alan-project 

상우님은 유효한 디폴트 json 을 넣어 파싱이 정상적으로 되도록 수정하신 반면,
제가 생각하는 코드는 json 파싱은 type safety 하지 않기 때문에 휴먼 에러 발생할 여지도 있고... 해서
아예 디폴트 객체를 반환하여 non-null로 만들어주는 것을 생각했어요


```kotlin
val domainVersionConfigModel = Gson().fromJson(
    remoteConfig.getString("version_update"),
    DomainVersionConfigModel::class.java
) ?: DomainVersionConfigModel(latestVersion = context.packageManager.getPackageInfo(context.packageName, 0).versionCode)
```

**Comment by alan-project** [comment]
> @alan-project
> 
> 음... 다른 것부터 이야기를 먼저 하면 `master` 브랜치로 commit 하는 것은 되도록 피하셨으면 해요. 혼자 하는 프로젝트라 그게 편하고 문제도 없긴 합니다만, 상우님께서 팀원들과 git으로 협업을 충분히 경험하신 것이 아니기에 (PR, 코드 리뷰 등) 되도록 혼자할 때에도 PR을 올려 이력 관리를 하는 것을 습관화하는 것이 좋을 것 같습니다. (아마 실무에서는 `master` 브랜치에 commit 권한 자체가 막혀있을 거에요.)
> 
> 1. 보통 Jira에 문제가 등록되면 (github issue에 문제가 꽂히면)
> 2. 관련된 브랜치를 따고,
> 3. 문제를 수정 후
> 4. PR을 올립니다.
> 5. 코드 리뷰를 거치고
> 6. merge를 합니다.
> 
> 단순히 이것 외에도 해당 PR과 Jira 티켓 (github issue) 사이에 link가 생기기 때문에 어떤 이슈를 어떤 PR에서 수정했는지 트래킹이 더 수월해져요. 반면 지금 `master` 브랜치에 바로 커밋하신 내용은 제가 리뷰하기도 어렵고, 상우님께서 코드 조각을 댓글로 올려주셔야 인지 가능한 부분도 있고요.

아..감사합니다. 다시 문제별로 브랜치 따서 PR로 진행해야겠네요.
 편하기도 하고 어느순간 커밋수에 눈이 멀어 초심을 잃었네요 ㅎㅎ



> @alan-project
> 
> 상우님은 유효한 디폴트 json 을 넣어 파싱이 정상적으로 되도록 수정하신 반면, 제가 생각하는 코드는 json 파싱은 type safety 하지 않기 때문에 휴먼 에러 발생할 여지도 있고... 해서 아예 디폴트 객체를 반환하여 non-null로 만들어주는 것을 생각했어요
> 
> ```kotlin
> val domainVersionConfigModel = Gson().fromJson(
>     remoteConfig.getString("version_update"),
>     DomainVersionConfigModel::class.java
> ) ?: DomainVersionConfigModel(latestVersion = context.packageManager.getPackageInfo(context.packageName, 0).versionCode)
> ```

아..코드 짜면서도, 이건 아닌데...싶었는데 데이터모델에 버전코드만 넣어서 넘겨주면 되겠네요.
나머지는 default 값들이 채워지고..이게 맞겠네요..
감사합니다!
